GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})

Assets = {
	Asset("ANIM", "anim/spell_icons_tallbird.zip"),
    Asset("ANIM","anim/tallbird_health.zip"),
    Asset("ANIM","anim/smallbird_basic_water.zip"),
    Asset("ANIM","anim/player_gaint_roll.zip"),
    Asset("SOUNDPACKAGE", "sound/tallbird_egg_oversized.fev"),
    Asset("SOUND", "sound/tallbird_egg_oversized.fsb"),
}

PrefabFiles = GetModConfigData('lovely_tallbird_family'..'skins') and {
    "tallbird",
    "tallbird_saddle",
    "tallbird_eggshell",
    "tallbird_skins",
    "teenbird_skins",
    "smallbird_skins",
    "tallbird_comb",
    "tallbird_buffs",
    "tallbird_eyefx",
    "lunar_tallbird_laser",
    "new_tallbirdnest",
    "beak_carrot_bird_rod",
    "tallbird_yolk",
    "armor_eggshell",
    "eggshellfx_armor",
    "hat_eggshell",
    "armor_halfshell",
    "tallbird_egg_oversized",
    "tallbird_egg_oversized_builder",
    "tallbird_bell",
}
or {
    "tallbird",
    "tallbird_saddle",
    "tallbird_eggshell",
    "tallbird_comb",
    "tallbird_buffs",
    "tallbird_eyefx",
    "lunar_tallbird_laser",
    "new_tallbirdnest",
    "beak_carrot_bird_rod",
    "tallbird_yolk",
    "armor_eggshell",
    "eggshellfx_armor",
    "hat_eggshell",
    "armor_halfshell",
    "tallbird_egg_oversized",
    "tallbird_egg_oversized_builder",
    "tallbird_bell",
}