STRINGS.NAMES.TALLBIRD_SADDLE="高鸟鞍椅"
STRINGS.RECIPE_DESC.TALLBIRD_SADDLE= "坐上它便可当高人，但安全后果自负"
STRINGS.NAMES.TALLBIRD_EGGSHELL1="高脚鸟蛋壳"
STRINGS.NAMES.TALLBIRD_EGGSHELL2="高脚鸟蛋壳"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TALLBIRD_EGGSHELL1 = "这是给小高鸟取名用的。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TALLBIRD_EGGSHELL2 = "这是给小高鸟取名用的"
--梳子
STRINGS.NAMES.TALLBIRD_COMB_FOLLOW = "梳子 集合"  --集合显示名字
STRINGS.NAMES.TALLBIRD_COMB_LEAVE = "梳子 解散"  --解散显示名字
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TALLBIRD_COMB_FOLLOW = "用来召集和驱散高鸟们的。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TALLBIRD_COMB_LEAVE = "用来召集和驱散高鸟们的。"
STRINGS.RECIPE_DESC.TALLBIRD_COMB_FOLLOW = "用来召集和驱散高鸟们的。"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_RETARGET1 = "鸟鸟安静下来。"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_RETARGET2 = "我们去揍扁敌人们。"
--角色检查台词
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TALLBIRD_SADDLE= "嗯，一个给高鸟用的鞍具，设计得挺巧妙。"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TALLBIRD_SADDLE = "同时折磨两个生命。"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TALLBIRD_SADDLE= "这玩意儿真能镇住那只凶鸟？别半道散架了。"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TALLBIRD_SADDLE= "大鸟的鞍…… 希望它别把沃尔夫冈甩下去！"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TALLBIRD_SADDLE= "竟有人为高鸟制作专用鞍具，真是新奇的发明。"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TALLBIRD_SADDLE= "我并不想花时间在上面保持平衡。"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TALLBIRD_SADDLE= "这是什么魔鬼点子。"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TALLBIRD_SADDLE= "我希望他不会记恨我曾料理过他的孩子。"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TALLBIRD_SADDLE= "鞍具简陋，却需无上勇气驾驭此猛禽！"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TALLBIRD_SADDLE= "为什么要欺负只有一个眼睛的动物！"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TALLBIRD_SADDLE= "大眼睛啾啾的椅子。"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TALLBIRD_SADDLE= "这太荒唐了。"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TALLBIRD_SADDLE= "我们可以骑大鸟啦！"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TALLBIRD_SADDLE= "沃比，你看我们能骑大鸟啦！"
STRINGS.CHARACTERS.WURT.DESCRIBE.TALLBIRD_SADDLE= "上面画了个大眼睛，吓人。"
STRINGS.CHARACTERS.WX78.DESCRIBE.TALLBIRD_SADDLE= "我要折磨你"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TALLBIRD_SADDLE= "哼！别盯着我！"

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_TRUSTEENSHIP = "这是别人的"
---中文
---骑乘高脚鸟低生命时的台词 写""里面
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH = "鸟快不行了，我应该救治它！"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH = "鸟和我的心都快要接近死亡了。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "该注意点鸟的健康状况如何了。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "大鸟好像受伤的很严重了。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "鸟儿的健康状况堪忧，需要救治。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "我应该注意一下鸟还剩下多少时间。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "我想我该给这鸟包扎下伤口了。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "鸟该需要一顿大餐来恢复活力了！"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "我的战骑受损严重！需要撤离！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "笨鸟受伤太多了！先逃命吧！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "啾啾朋友受伤很多了！"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "再挨几下，暗影之王将在一只鸟身上陨落了。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "我好像听到大鸟骨头断裂的声音！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "大鸟该停下来歇会，吃点零食了！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "大鸟受伤太多了！。浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "警告：有机生命受损严重"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "哦！鸟受伤了！需要治疗！"


---给高脚鸟装其他鞍失败的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ISTALLBIRD_NOTSADDLE = "我应该制作一款更适合鸟类的。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_ISTALLBIRD_NOTSADDLE = "不是什么都能凑合的。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这么干会出问题。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这重量对大鸟来说不合适。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这种鞍不是给高鸟的。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "呃…我不知道它想要什么。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "臭鸟的心思难以捉摸。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "我想有更适合它体型的套装。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这配不上我勇猛的坐骑。"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "你长得这么笨！就别挑剔了！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "啾啾不喜欢。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "真没礼貌。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "大鸟不喜欢这个玩具。"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "应该给大鸟朋友们更适合它的。"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这不好玩。浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "错误：无法匹配"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "朋友觉得这个玩笑不好笑。"


---给其他坐骑装高脚鸟鞍失败的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_NOTTALLBIRD_ISSADDLE = "不对，这是给高脚鸟用的。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_NOTTALLBIRD_ISSADDLE = "它拒绝我了。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这尺寸可不是给它的。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "沃尔夫冈感觉它不喜欢。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这是给陆鸟类用的特制鞍具。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "真是浪费时间。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这是拿来绑讨厌的鸟的。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "客人不喜欢这套尺寸。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "此兽不配此鞍。"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这是拿来抓笨大鸟的！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "应该送给大眼睛啾啾。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "不是给它用的，别白费力气了。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这个不是这么玩的。"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "我觉得一定是哪里出了错。"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "浮浪噗。不要算了！"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "目标错误"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "我才不给你呢！"


---给野生高脚鸟装鞍失败的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_ISWILD = "这么做它会啄我的脑袋。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_ISWILD = "我们的友谊从未开始。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_ISWILD= "这家伙会把我啄成筛子。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_ISWILD= "沃尔夫冈从不强求动物们。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_ISWILD= "这样会激怒它，不要冒险。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_ISWILD= "我想我们没有和谈余地。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_ISWILD= "我干嘛要没事找事。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_ISWILD= "我想我们应该先培养友谊？"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_ISWILD= "我无心冒犯此兽。"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_ISWILD= "如果它被我烤熟了，或许就行了。"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_ISWILD= "植物跟啾啾可以做朋友吗？"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_ISWILD= "除非我不要命了。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_ISWILD= "如果我们从小开始玩，或许可以。"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_ISWILD= "这好像不太礼貌……"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_ISWILD= "鸟不相信鱼人。浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_ISWILD= "警告：可能引发潜在威胁"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_ISWILD= "它一点也不好欺负。"


---切换攻击方式回旋踢的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_ATKLEG = "大鸟，施展你的双腿！"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_ATKLEG = "踢碎这些烦人的东西。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_ATKLEG= "大鸟，让我们把它们踢飞！"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_ATKLEG= "用你强壮的大脚去揍敌人！"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_ATKLEG= "发挥你高挑长腿的优势！"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_ATKLEG= "走吧，顺便踏平我们的路。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_ATKLEG= "去把敌人踹飞！"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_ATKLEG= "大鸟！去把它们踏成肉饼！"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_ATKLEG= "以回旋之踢，痛击周遭宵小！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_ATKLEG= "狠狠的踢坏蛋的屁股！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_ATKLEG= "用脚转起来！"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_ATKLEG= "去把敌人踩在脚下。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_ATKLEG= "大鸟的腿保护我们！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_ATKLEG= "大鸟准备起舞！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_ATKLEG= "腿真好用！浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_ATKLEG= "启用范围打击程序"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_ATKLEG= "用脚踢飞它们，更有意思！"


---切换攻击方式非回旋踢的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_NOTATKLEG = "大鸟！动用你智慧的头脑！"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_NOTATKLEG = "用你的尖喙刺穿它们。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_NOTATKLEG= "走！我们去把它们啄成筛子！"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_NOTATKLEG= "沃尔夫冈赞成用铁头功！"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_NOTATKLEG= "我这身体可遭不住这样晃！"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_NOTATKLEG= "别晃了，头都晕了。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_NOTATKLEG= "我就知道这鸟想整蛊我！"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_NOTATKLEG= "我想我的脑浆要晃成浆糊了！"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_NOTATKLEG= "纵有眩晕，亦要以喙破敌！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_NOTATKLEG= "坏蛋和我总要倒一个！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_NOTATKLEG= "用嘴巴打人！"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_NOTATKLEG= "别忘了你头上还有个人！"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_NOTATKLEG= "我得抱紧大鸟的头了！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_NOTATKLEG= "准备进行飞行员抗眩晕锻炼！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_NOTATKLEG= "太晕了！浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_NOTATKLEG= "警告：平衡模块异常。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_NOTATKLEG= "啄得真猛，灵魂都要晃散咯！"


---给高脚鸟树枝/采下的草 不熟
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_NOFAMILY = "我想我得多带大几只它们的孩子。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_NOFAMILY = "它们家族还不认同我……"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_NOFAMILY= "还要养大更多的鸟。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_NOFAMILY= "沃尔夫冈应该多孵几个小鸟宝宝。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_NOFAMILY= "只有养大它们家族一定数量才能获得认同。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_NOFAMILY= "还要花多少时间在育鸟身上……？"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_NOFAMILY= "饶了我吧……还要养大更多臭鸟它才接受。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_NOFAMILY= "我想我得带大更多鸟才能融入鸟们。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_NOFAMILY= "还需养大更多雏鸟，才可授令随行。"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_NOFAMILY= "什么？还要养大更多臭臭的笨小鸟？！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_NOFAMILY= "要养更多啾啾。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_NOFAMILY= "还要养大更多你们这些家伙？把我当仆人了吗？"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_NOFAMILY= "我们需要让更多小鸟长高高！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_NOFAMILY= "沃比！我们还要孵化更多高鸟！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_NOFAMILY= "要养更多鸟！浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_NOFAMILY= "需要更多鸟类单位成熟。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_NOFAMILY= "还要养大更多你们这些小淘气鬼！"

---月亮
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_LUNAR_TALLBIRD = "让鸟群施展月亮的力量吧！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DETACH_BUFF_LUNAR_TALLBIRD = "月亮的力量消失了。"

---暗影
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_SHADOW_TALLBIRD = "让鸟群施展暗影的力量吧！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DETACH_BUFF_SHADOW_TALLBIRD = "暗影的力量消失了。"

---高脚鸟遮阴（人物过热，成年鸟靠过来给人遮阳）
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_SHELETERED = "感谢鸟儿帮忙遮挡烈日，感觉凉快些了。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_SHELETERED = "接受自己是移动遮阳伞的命运了吗？"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_SHELETERED= "谢谢鸟伙计，不用找树下乘凉了。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_SHELETERED= "沃尔夫冈的遮阳大伞们来了！"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_SHELETERED= "我想我能在鸟儿的阴影下得到一些庇护。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_SHELETERED= "活了这么久还没什么人为我撑伞，你们是第一个。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_SHELETERED= "臭鸟们来帮我遮阳了？有意思…"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_SHELETERED= "感谢鸟朋友们，我感觉凉快多了！"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_SHELETERED= "巨鸟为我遮蔽烈日的灼烧！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_SHELETERED= "这阴凉还挺舒服。"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_SHELETERED= "啾啾底下真凉快。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_SHELETERED= "很好，有尽职到帮主人撑伞的责任。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_SHELETERED= "我们在大鸟的阴影下乘凉！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_SHELETERED= "太好了！你们帮我挡住太阳啦！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_SHELETERED= "凉！好舒服！"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_SHELETERED= "过热风险 降低。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_SHELETERED= "阴凉，正合我意。"

---暖和（人物过冷，鸟靠过来给人供暖）
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_WARM = "鸟儿的羽毛让我感觉很暖和。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_WARM = "这些毛球为我驱散寒意。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_WARM= "你们怎么知道我快要冷死了？真贴心。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_WARM= "暖和极了，好鸟宝宝们。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_WARM= "鸟儿们靠过来取暖，真贴心。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_WARM= "谢谢你们有空来温暖我……"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_WARM= "呃，臭鸟们怎么靠这么近！算了……"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_WARM= "谢天谢地，有温暖的鸟儿们簇拥。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_WARM= "这些猛禽的羽翼为我抵御严寒！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_WARM= "哼，勉强借你们的毛暖一下。"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_WARM= "暖暖的啾啾羽毛。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_WARM= "我的鸟仆人们过来给我供暖了，还算凑合。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_WARM= "大鸟朋友们真暖和！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_WARM= "哇…… 你们的羽毛好暖和呀，太谢谢啦！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_WARM= "暖！羽毛好暖！"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_WARM= "温度提升。有机体 有用。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_WARM= "呵，这些小毛球倒也懂得温暖灵魂。"

---小鸟 取暖（人物过冷，小鸟靠过来给人供暖）
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_SMALLBIRD_WARM = "小鸟们贴在身上，冰凉的手暖和起来了。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_SMALLBIRD_WARM = "毛茸茸的温暖……比墓地的风好多了。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_SMALLBIRD_WARM= "小东西们在发抖呢——哦，是在替我发抖。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_SMALLBIRD_WARM= "小鸟们觉得沃尔夫冈像个大鸟妈妈！"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_SMALLBIRD_WARM= "小鸟凭借本能接近热源，倒也不失为一种生存智慧。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_SMALLBIRD_WARM= "小时候我总喜欢把小鸟捧在手心取暖……"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_SMALLBIRD_WARM= "嘿！小鸟崽子们贴得比Lucy还紧！"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_SMALLBIRD_WARM= "唔…小鸟的热量可以让面团发酵得更快。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_SMALLBIRD_WARM= "小鸟们！与我一同抵御这寒冬吧！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_SMALLBIRD_WARM= "还没我的打火机暖和…不过挺可爱的。"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_SMALLBIRD_WARM= "小鸟 暖暖 喜欢。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_SMALLBIRD_WARM= "你们的羽毛尚能派上一点用场。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_SMALLBIRD_WARM= "小鸟朋友们挤在我们脚边，好暖和呀！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_SMALLBIRD_WARM= "哇！它们靠在我身上睡着了！嘘——"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_SMALLBIRD_WARM= "小毛毛，暖呼呼！"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_SMALLBIRD_WARM= "热传导效率 尚可。有机体 幼崽 留用。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_SMALLBIRD_WARM= "小灵魂们热乎乎的，真令人欣慰。"

---小鸟遮阴（人物过热，小鸟靠过来给人遮阳）
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_SMALLBIRD_SHELETERED = "你们的小翅膀挡不住多少太阳……但谢了。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_SMALLBIRD_SHELETERED = "小小的影子，总比没有好。和我的生活一样。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_SMALLBIRD_SHELETERED= "遮不了多少阴，但心领了，小毛球们。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_SMALLBIRD_SHELETERED= "小鸟们想做沃尔夫冈的迷你太阳伞！"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_SMALLBIRD_SHELETERED= "虽然微不足道，但这份好意值得肯定。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_SMALLBIRD_SHELETERED= "你们呀……等翅膀长硬了再给我遮阳也不迟。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_SMALLBIRD_SHELETERED= "行吧，哪怕就遮住一根胡子，也算凉快了。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_SMALLBIRD_SHELETERED= "别晒着小鸟们了，来帽子底下躲躲。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_SMALLBIRD_SHELETERED= "小鸟战士！为本将军带来一片阴凉！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_SMALLBIRD_SHELETERED= "嗤，就这点影子够干嘛……算了随你们便。"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_SMALLBIRD_SHELETERED= "啾啾 树荫 凉凉。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_SMALLBIRD_SHELETERED= "遮阳这种事，等你们长大了再干也不迟。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_SMALLBIRD_SHELETERED= "小鸟们想帮我们挡住太阳，好可爱！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_SMALLBIRD_SHELETERED= "虽然影子很小，但有这份心意就够了！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_SMALLBIRD_SHELETERED= "啾啾凉，舒服服。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_SMALLBIRD_SHELETERED= "遮阳率 不足5%。但算法 认可 这份努力。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_SMALLBIRD_SHELETERED= "小灵魂们的好意，我可不能辜负呀。"

---生成切换
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_SPAWNER = "现在这个巢穴会出生野生高脚鸟。"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_NO_SPAWNER = "现在这个巢穴不会出生野生高脚鸟了。"

---新巢穴（放置）
STRINGS.NAMES.NEW_TALLBIRDNEST = "高脚鸟巢"
---威尔逊
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NEW_TALLBIRDNEST = "这是我亲手做的巢，比野外的结实多了。"
---温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.NEW_TALLBIRDNEST = "人工的巢，也囚不住终将离开的生命。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.NEW_TALLBIRDNEST = "手工打造，品质保证。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.NEW_TALLBIRDNEST = "沃尔夫冈建的大巢，又大又牢固！"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NEW_TALLBIRDNEST = "结构合理的人工巢穴，值得记录下来。"
---旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.NEW_TALLBIRDNEST= "亲手做的，比起野外那些算是个升级。"
---伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.NEW_TALLBIRDNEST= "手工巢，鸟儿们该知足了。"
---沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.NEW_TALLBIRDNEST= "精致的巢穴，比野味餐馆还讲究。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NEW_TALLBIRDNEST= "此巢出于我手，鸟儿当以此为荣！"
---薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.NEW_TALLBIRDNEST= "自己做的，至少不会长虫子。"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.NEW_TALLBIRDNEST= "植物做的巢，啾啾喜欢。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.NEW_TALLBIRDNEST= "至少比野外那些破巢体面。"
---韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.NEW_TALLBIRDNEST= "我们亲手给小鸟朋友搭的新家！"
---沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.NEW_TALLBIRDNEST= "这是沃比和我一起给鸟儿做的窝！"
---沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.NEW_TALLBIRDNEST= "自己做的小窝，浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.DESCRIBE.NEW_TALLBIRDNEST= "人工巢 已就绪。优于 天然版。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.NEW_TALLBIRDNEST= "亲手做的巢，爱意满满呢。"

---新巢穴（物品）
STRINGS.NAMES.NEW_TALLBIRDNEST_ITEM="高脚鸟巢"
---配方描述
STRINGS.RECIPE_DESC.NEW_TALLBIRDNEST_ITEM= "取缔乱搭旧巢，规划宜居新居所。"

---威尔逊
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NEW_TALLBIRDNEST_ITEM = "拿着它，到哪都能给鸟儿安个家。"
---温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.NEW_TALLBIRDNEST_ITEM = "一个待命的坟墓，等我去找个地方放下。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.NEW_TALLBIRDNEST_ITEM = "赶紧安放好，等着孵小鸟。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.NEW_TALLBIRDNEST_ITEM = "沃尔夫冈拿着小鸟未来的家！"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NEW_TALLBIRDNEST_ITEM = "便携式巢穴，找到合适的地方就能安置。"
---旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "拿在手里，等找到好地方再放下。"
---伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "就在我手上，放下去就是个鸟窝。"
---沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "手里拎着个未来的鸟巢餐厅。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "此巢紧握我手，待我择地安放！"
---薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "放下去就能孵小鸟了，快！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "手上拿着啾啾以后的家。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "放好它，就会有新的仆人了。"
---韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "看，小鸟未来的家就在我们手上！"
---沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "我拿着它，找个好地方放下就行！"
---沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "孵小毛毛！浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "巢穴模块 手持中。待部署。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.NEW_TALLBIRDNEST_ITEM= "一个小巢捧在手里，等找到好地方就放下。"

STRINGS.TALLBIRD_NAMED_WRITEABLE = {
    prompt = "给你的鸟起个名字",
    noname = "无名氏",
    text0 = "的鸟",
    text1 = "取消",
    text2 = "随机",
    text3 = "确认"
}

STRINGS.TALLBIRD_ACTIONS_NAMED = {
    JOUST = "冲锋",
    DASH = "暗影冲刺",
    PLANAR = "位面化",
    LEAVE = "筑巢穴",
    NAMED = "命名",
    CHOP = "砍",
    MINE = "开采",
    DIG = "挖",
    HAMMER = "敲",
    SCYTHE = "收割",
    COLLECT = "收集",
    GATHER = "集合",
    DISSOLVE = "解散",
    SPAWN = "生成切换"
}

STRINGS.TALLBIRD_FAMILY_FAME = "声望"
