STRINGS.NAMES.TALLBIRD_SADDLE="高鸟鞍椅"
STRINGS.RECIPE_DESC.TALLBIRD_SADDLE= "坐上它便可当高人，但安全后果自负"
STRINGS.NAMES.TALLBIRD_EGGSHELL1="高脚鸟蛋壳"
STRINGS.NAMES.TALLBIRD_EGGSHELL2="高脚鸟蛋壳"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TALLBIRD_EGGSHELL1 = "这是给小高鸟取名用的。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TALLBIRD_EGGSHELL2 = "这是给小高鸟取名用的"
--角色检查台词
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TALLBIRD_SADDLE= "嗯，一个给高鸟用的鞍具，设计得挺巧妙。"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TALLBIRD_SADDLE = "同时折磨两个生命。"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TALLBIRD_SADDLE= "这玩意儿真能镇住那只凶鸟？别半道散架了。"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TALLBIRD_SADDLE= "大鸟的鞍…… 希望它别把沃尔夫冈甩下去！"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TALLBIRD_SADDLE= "竟有人为高鸟制作专用鞍具，真是新奇的发明。"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TALLBIRD_SADDLE= "我并不想花时间在上面保持平衡。"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TALLBIRD_SADDLE= "这是什么魔鬼点子。"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TALLBIRD_SADDLE= "我希望他不会记恨我曾料理过他的孩子。"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TALLBIRD_SADDLE= "鞍具简陋，却需无上勇气驾驭此猛禽！"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TALLBIRD_SADDLE= "为什么要欺负只有一个眼睛的动物！"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TALLBIRD_SADDLE= "大眼睛啾啾的椅子。"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TALLBIRD_SADDLE= "这太荒唐了。"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TALLBIRD_SADDLE= "我们可以骑大鸟啦！"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TALLBIRD_SADDLE= "沃比，你看我们能骑大鸟啦！"
STRINGS.CHARACTERS.WURT.DESCRIBE.TALLBIRD_SADDLE= "上面画了个大眼睛，吓人。"
STRINGS.CHARACTERS.WX78.DESCRIBE.TALLBIRD_SADDLE= "我要折磨你"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TALLBIRD_SADDLE= "哼！别盯着我！"


---中文
---骑乘高脚鸟低生命时的台词 写""里面
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH = "鸟快不行了，我应该救治它！"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH = "鸟和我的心都快要接近死亡了。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "该注意点鸟的健康状况如何了。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "大鸟好像受伤的很严重了。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "鸟儿的健康状况堪忧，需要救治。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "我应该注意一下鸟还剩下多少时间。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "我想我该给这鸟包扎下伤口了。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "鸟该需要一顿大餐来恢复活力了！"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "我的战骑受损严重！需要撤离！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "笨鸟受伤太多了！先逃命吧！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "啾啾朋友受伤很多了！"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "再挨几下，暗影之王将在一只鸟身上陨落了。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "我好像听到大鸟骨头断裂的声音！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "大鸟该停下来歇会，吃点零食了！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "大鸟受伤太多了！。浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "警告：有机生命受损严重"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_MOUNT_LOWHEALTH= "哦！鸟受伤了！需要治疗！"


---给高脚鸟装其他鞍失败的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ISTALLBIRD_NOTSADDLE = "我应该制作一款更适合鸟类的。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_ISTALLBIRD_NOTSADDLE = "不是什么都能凑合的。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这么干会出问题。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这重量对大鸟来说不合适。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这种鞍不是给高鸟的。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "呃…我不知道它想要什么。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "臭鸟的心思难以捉摸。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "我想有更适合它体型的套装。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这配不上我勇猛的坐骑。"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "你长得这么笨！就别挑剔了！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "啾啾不喜欢。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "真没礼貌。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "大鸟不喜欢这个玩具。"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "应该给大鸟朋友们更适合它的。"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "这不好玩。浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "错误：无法匹配"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_ISTALLBIRD_NOTSADDLE= "朋友觉得这个玩笑不好笑。"


---给其他坐骑装高脚鸟鞍失败的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_NOTTALLBIRD_ISSADDLE = "不对，这是给高脚鸟用的。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_NOTTALLBIRD_ISSADDLE = "它拒绝我了。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这尺寸可不是给它的。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "沃尔夫冈感觉它不喜欢。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这是给陆鸟类用的特制鞍具。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "真是浪费时间。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这是拿来绑讨厌的鸟的。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "客人不喜欢这套尺寸。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "此兽不配此鞍。"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这是拿来抓笨大鸟的！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "应该送给大眼睛啾啾。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "不是给它用的，别白费力气了。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "这个不是这么玩的。"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "我觉得一定是哪里出了错。"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "浮浪噗。不要算了！"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "目标错误"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_NOTTALLBIRD_ISSADDLE= "我才不给你呢！"


---给野生高脚鸟装鞍失败的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_ISWILD = "这么做它会啄我的脑袋。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_ISWILD = "我们的友谊从未开始。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_ISWILD= "这家伙会把我啄成筛子。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_ISWILD= "沃尔夫冈从不强求动物们。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_ISWILD= "这样会激怒它，不要冒险。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_ISWILD= "我想我们没有和谈余地。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_ISWILD= "我干嘛要没事找事。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_ISWILD= "我想我们应该先培养友谊？"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_ISWILD= "我无心冒犯此兽。"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_ISWILD= "如果它被我烤熟了，或许就行了。"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_ISWILD= "植物跟啾啾可以做朋友吗？"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_ISWILD= "除非我不要命了。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_ISWILD= "如果我们从小开始玩，或许可以。"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_ISWILD= "这好像不太礼貌……"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_ISWILD= "鸟不相信鱼人。浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_ISWILD= "警告：可能引发潜在威胁"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_ISWILD= "它一点也不好欺负。"


---切换攻击方式回旋踢的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_ATKLEG = "大鸟，施展你的双腿！"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_ATKLEG = "踢碎这些烦人的东西。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_ATKLEG= "大鸟，让我们把它们踢飞！"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_ATKLEG= "用你强壮的大脚去揍敌人！"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_ATKLEG= "发挥你高挑长腿的优势！"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_ATKLEG= "走吧，顺便踏平我们的路。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_ATKLEG= "去把敌人踹飞！"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_ATKLEG= "大鸟！去把它们踏成肉饼！"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_ATKLEG= "以回旋之踢，痛击周遭宵小！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_ATKLEG= "狠狠的踢坏蛋的屁股！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_ATKLEG= "用脚转起来！"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_ATKLEG= "去把敌人踩在脚下。"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_ATKLEG= "大鸟的腿保护我们！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_ATKLEG= "大鸟准备起舞！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_ATKLEG= "腿真好用！浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_ATKLEG= "启用范围打击程序"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_ATKLEG= "用脚踢飞它们，更有意思！"


---切换攻击方式非回旋踢的台词
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_NOTATKLEG = "大鸟！动用你智慧的头脑！"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_NOTATKLEG = "用你的尖喙刺穿它们。"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_NOTATKLEG= "走！我们去把它们啄成筛子！"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_NOTATKLEG= "沃尔夫冈赞成用铁头功！"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_NOTATKLEG= "我这身体可遭不住这样晃！"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_NOTATKLEG= "别晃了，头都晕了。"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_NOTATKLEG= "我就知道这鸟想整蛊我！"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_NOTATKLEG= "我想我的脑浆要晃成浆糊了！"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_NOTATKLEG= "纵有眩晕，亦要以喙破敌！"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_NOTATKLEG= "坏蛋和我总要倒一个！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_NOTATKLEG= "用嘴巴打人！"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_NOTATKLEG= "别忘了你头上还有个人！"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_NOTATKLEG= "我得抱紧大鸟的头了！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_NOTATKLEG= "准备进行飞行员抗眩晕锻炼！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_NOTATKLEG= "太晕了！浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_NOTATKLEG= "警告：平衡模块异常。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_NOTATKLEG= "啄得真猛，灵魂都要晃散咯！"


---给高脚鸟树枝/采下的草 不熟
---威尔逊
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_TALLBIRD_NOFAMILY = "我想我得多带大几只它们的孩子。"
---温蒂
STRINGS.CHARACTERS.WENDY.ANNOUNCE_TALLBIRD_NOFAMILY = "它们家族还不认同我……"
---薇诺娜
STRINGS.CHARACTERS.WINONA.ANNOUNCE_TALLBIRD_NOFAMILY= "还要养大更多的鸟。"
---沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_TALLBIRD_NOFAMILY= "沃尔夫冈应该多孵几个小鸟宝宝。"
---薇克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TALLBIRD_NOFAMILY= "只有养大它们家族一定数量才能获得认同。"
---旺达
STRINGS.CHARACTERS.WANDA.ANNOUNCE_TALLBIRD_NOFAMILY= "还要花多少时间在育鸟身上……？"
---伍迪
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_TALLBIRD_NOFAMILY= "饶了我吧……还要养大更多臭鸟它才接受。"
---沃利
STRINGS.CHARACTERS.WARLY.ANNOUNCE_TALLBIRD_NOFAMILY= "我想我得带大更多鸟才能融入鸟们。"
---薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_TALLBIRD_NOFAMILY= "还需养大更多雏鸟，才可授令随行。"
---薇洛
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_TALLBIRD_NOFAMILY= "什么？还要养大更多臭臭的笨小鸟？！"
---沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_TALLBIRD_NOFAMILY= "要养更多啾啾。"
---麦斯威尔
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_TALLBIRD_NOFAMILY= "还要养大更多你们这些家伙？把我当仆人了吗？"
---韦伯
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_TALLBIRD_NOFAMILY= "我们需要让更多小鸟长高高！"
---沃尔特
STRINGS.CHARACTERS.WALTER.ANNOUNCE_TALLBIRD_NOFAMILY= "沃比！我们还要孵化更多高鸟！"
---沃特
STRINGS.CHARACTERS.WURT.ANNOUNCE_TALLBIRD_NOFAMILY= "要养更多鸟！浮浪噗。"
---WX-78
STRINGS.CHARACTERS.WX78.ANNOUNCE_TALLBIRD_NOFAMILY= "需要更多鸟类单位成熟。"
---沃拓克斯
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_TALLBIRD_NOFAMILY= "还要养大更多你们这些小淘气鬼！"